version: "3.8"

services:
  mariadb:
    image: mariadb
    ports:
    - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: powerdns
      MYSQL_USER: powerdns
      MYSQL_PASSWORD: powerdns

  powerdns:
    depends_on:
      - mariadb
    image: psitrax/powerdns:v4.3
    ports:
      - "53:53"
      - "53:53/udp"
      - "9090:80"
    links:
      - mariadb
    environment:
      MYSQL_HOST: mariadb
      MYSQL_DB: powerdns
      MYSQL_USER: powerdns
      MYSQL_PASS: powerdns
      MYSQL_DNSSEC: "yes"
    command: [
        "--webserver=yes",
        "--webserver-address=0.0.0.0",
        "--webserver-port=80",
        "--webserver-allow-from=0.0.0.0/0",
        "--api=yes",
        "--api-key=cray",
        "--disable-syslog=yes",
        "--loglevel=9",
        "--log-dns-queries=yes",
        "--log-dns-details=yes",
        "--query-logging=yes",
        "--default-soa-edit=INCEPTION-INCREMENT",
    ]
