apiVersion: v2
name: cray-powerdns-manager
version: 0.5.0
description: Kubernetes Deployment for PowerDNS Manager
keywords:
  - cray-powerdns-manager
home: https://github.com/Cray-HPE/cray-powerdns-manager
dependencies:
  - name: cray-service
    version: "~7.0.0"
    repository: "https://artifactory.algol60.net/artifactory/csm-helm-charts/"
maintainers:
  - name: dle-hpe
  - name: SeanWallace
  - name: spillerc-hpe
appVersion: 0.5.0
annotations:
  artifacthub.io/changes: |
    - kind: security
      description: Refactor to use patched CSM images
      links:
        - name: Github Issue
          url: https://github.com/Cray-HPE/cray-powerdns-manager/issues/11
        - name: Github PR
          url: https://github.com/Cray-HPE/cray-powerdns-manager/pull/10
  artifacthub.io/images: |
    - name: cray-powerdns-manager
      image: artifactory.algol60.net/csm-docker/stable/cray-powerdns-manager:0.4.0
artifacthub.io/license: MIT
