cray-service:
  type:               "Deployment"
  nameOverride:       "cray-powerdns-manager"
  fullnameOverride:   "cray-powerdns-manager"
  serviceAccountName: "jobs-watcher"
  replicaCount:       1
  strategy:
    type: Recreate
  containers:
    cray-powerdns-manager:
      name: "cray-powerdns-manager"
      image:
        repository: "cray/cray-powerdns-manager"
        #pullPolicy: Always
      ports:
        - name:          http
          containerPort: 8080
      env:
        - name: BASE_DOMAIN
          valueFrom:
            configMapKeyRef:
              name: cray-powerdns-manager-config
              key: base_domain
        - name: MASTER_SERVER
          valueFrom:
            configMapKeyRef:
              name: cray-powerdns-manager-config
              key:  master_server
        - name: SLAVE_SERVERS
          valueFrom:
            configMapKeyRef:
              name: cray-powerdns-manager-config
              key:  slave_servers
        - name:  PDNS_URL
          value: "http://cray-dns-powerdns-api:8081"
        - name: PDNS_API_KEY
          valueFrom:
            secretKeyRef:
              name: cray-powerdns-credentials
              key:  pdns_api_key
        - name: KEY_DIRECTORY
          value: "/keys"
      livenessProbe:
        httpGet:
          port: 8080
          path: /v1/liveness
        initialDelaySeconds: 10
        periodSeconds:       30
      readinessProbe:
        httpGet:
          port: 8080
          path: /v1/readiness
        initialDelaySeconds: 15
        periodSeconds:       30
      volumeMounts:
        - name: dnssec-keys
          mountPath: "/keys"
          readOnly: true
  volumes:
    - name: dnssec-keys
      secret:
        secretName: dnssec-keys
  ingress:
    enabled: true
    prefix:  "/apis/powerdns-manager/"
    uri:     "/"

manager:
  master_server: ""
  slave_servers: ""
  notify_domains: ""
