#
# MIT License
#
# (C) Copyright 2022 Hewlett Packard Enterprise Development LP
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
cray-service:
  type: Deployment
  nameOverride: cray-powerdns-manager
  fullnameOverride: cray-powerdns-manager
  priorityClassName: csm-high-priority-service
  serviceAccountName: jobs-watcher
  replicaCount: 1
  strategy:
    type: Recreate
  containers:
    cray-powerdns-manager:
      name: cray-powerdns-manager
      image:
        repository: artifactory.algol60.net/csm-docker/stable/cray-powerdns-manager
        pullPolicy: IfNotPresent
      ports:
        - name: http
          containerPort: 8080
      env:
        - name: BASE_DOMAIN
          valueFrom:
            configMapKeyRef:
              name: cray-powerdns-manager-config
              key: base_domain
        - name: PRIMARY_SERVER
          valueFrom:
            configMapKeyRef:
              name: cray-powerdns-manager-config
              key: primary_server
        - name: SECONDARY_SERVERS
          valueFrom:
            configMapKeyRef:
              name: cray-powerdns-manager-config
              key: secondary_servers
        - name: NOTIFY_ZONES
          valueFrom:
            configMapKeyRef:
              name: cray-powerdns-manager-config
              key: notify_zones
        - name: PDNS_URL
          value: http://cray-dns-powerdns-api:8081
        - name: PDNS_API_KEY
          valueFrom:
            secretKeyRef:
              name: cray-powerdns-credentials
              key: pdns_api_key
        - name: KEY_DIRECTORY
          value: /keys
      livenessProbe:
        httpGet:
          port: 8080
          path: /v1/liveness
        initialDelaySeconds: 10
        periodSeconds: 30
      readinessProbe:
        httpGet:
          port: 8080
          path: /v1/readiness
        initialDelaySeconds: 15
        periodSeconds: 30
      volumeMounts:
        - name: dnssec-keys
          mountPath: /keys
          readOnly: true
    cray-externaldns-manager:
      name: cray-externaldns-manager
      image:
        repository: artifactory.algol60.net/csm-docker/stable/cray-powerdns-manager
        pullPolicy: IfNotPresent
      command:
        - /usr/local/bin/cray-externaldns-manager
      ports:
        - name: edns-http
          containerPort: 8081
      env:
        - name: PDNS_URL
          value: http://cray-dns-powerdns-api:8081
        - name: PDNS_API_KEY
          valueFrom:
            secretKeyRef:
              name: cray-powerdns-credentials
              key: pdns_api_key
      livenessProbe:
        httpGet:
          port: 8081
          path: /v1/liveness
        initialDelaySeconds: 10
        periodSeconds: 30
      readinessProbe:
        httpGet:
          port: 8081
          path: /v1/readiness
        initialDelaySeconds: 15
        periodSeconds: 30
  ingress:
    enabled: true
    prefix: /apis/powerdns-manager/
    uri: /
manager:
  primary_server: ""
  secondary_servers: ""
  notify_zones: ""
  base_domain: example.com
global:
  chart:
    name: cray-powerdns-manager
    version: 0.8.2
  appVersion: 0.8.2
