apiVersion: v1
kind: ConfigMap
metadata:
  name: cray-powerdns-manager-config
data:
  primary_server: {{ .Values.manager.primary_server | default "" | quote }}
  secondary_servers: {{ .Values.manager.secondary_servers | default "" | quote }}
  base_domain: {{ required "manager.base_domain is not set in customizations.yaml" .Values.manager.base_domain }}
  notify_zones: {{ .Values.manager.notify_zones | default "" | quote }}
